### ISSUE TITLE
피아노 건반 클릭 시 사운드 재생

### ISSUE THREAD

**Issue by pingulee** [PinguLee/Together-Piano#3]
- [x] 건반 신호 (click, keydown, midi 신호) 3가지로 구현
- [x] 피아노 건반 신호 입력 받을 시 그에 맞는 사운드 재생
- [x] 건반 누르고 있을 시 소리가 지속되는 서스테인 기능 구현
- [x] 건반을 바로 땔 시 스타카토 기능 구현

**Comment by PinguLee** [comment]
완료
